/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                "tertiary-container": "#1a1c1c",
                "surface": "#f9f9f9",
                "outline-variant": "#cfc4c5",
                "inverse-surface": "#2f3131",
                "on-secondary-fixed": "#1b1c1c",
                "on-primary-fixed": "#1b1b1b",
                "on-primary": "#ffffff",
                "inverse-on-surface": "#f1f1f1",
                "on-tertiary": "#ffffff",
                "error-container": "#ffdad6",
                "inverse-primary": "#c6c6c6",
                "error": "#ba1a1a",
                "primary-fixed-dim": "#c6c6c6",
                "outline": "#7e7576",
                "primary-fixed": "#e2e2e2",
                "surface-variant": "#e2e2e2",
                "secondary-fixed-dim": "#c7c6c6",
                "tertiary-fixed-dim": "#c6c6c6",
                "on-surface": "#1a1c1c",
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "surface-tint": "#5e5e5e",
                "on-secondary-fixed-variant": "#464747",
                "secondary-fixed": "#e3e2e2",
                "surface-container": "#eeeeee",
                "on-background": "#1a1c1c",
                "background": "#f9f9f9",
                "on-error": "#ffffff",
                "surface-container-highest": "#e2e2e2",
                "secondary": "#5e5e5e",
                "primary": "#000000",
                "on-primary-fixed-variant": "#474747",
                "surface-container-low": "#f3f3f3",
                "on-tertiary-fixed-variant": "#454747",
                "on-surface-variant": "#4c4546",
                "on-primary-container": "#848484",
                "tertiary": "#000000",
                "secondary-container": "#e3e2e2",
                "on-secondary-container": "#646464",
                "surface-dim": "#dadada",
                "tertiary-fixed": "#e2e2e2",
                "surface-container-high": "#e8e8e8",
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#1a1c1c",
                "surface-bright": "#f9f9f9",
                "primary-container": "#1b1b1b",
                "on-tertiary-container": "#838484"
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem"
            },
            spacing: {
                gutter: "24px",
                "container-margin-desktop": "64px",
                unit: "8px",
                "section-gap": "80px",
                "container-margin-mobile": "24px"
            },
            fontFamily: {
                "headline-xl-mobile": ["Geist"],
                "label-sm": ["Geist"],
                "body-md": ["Geist"],
                "label-md": ["Geist"],
                "headline-lg": ["Geist"],
                "body-lg": ["Geist"],
                "headline-xl": ["Geist"]
            },
            fontSize: {
                "headline-xl-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
                "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
                "headline-lg": ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "headline-xl": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }]
            }
        },
    },
    plugins: [],
}
